# -*- coding: utf-8 -*-

import tensorflow as tf
import numpy as np
from inference.tf.tf_dataset_generator import RowParser


class ExampleParser(RowParser):

    def __init__(self):
        pass

    def _gen_key(self, row, popitem_index, item_id):
        discount = row[3]
        label = row[4]
        vopenid = row[1]
        worldid = row[2]
        return vopenid, worldid, item_id, popitem_index, discount, label

    def parse(self, row):
        """ parse an example
        :param row: input tuple. When used in pyspark, input generated by 
            rdd row is tuple.
        :return: tuple of native type or list type
        """

        # Concatenate item feature and user feature and parse user feature
        # 用户特征中 10, 11, 12, 18, 20, 22, 23 列为string类型，由 itempools 中各个item的特征由逗号拼接组成，需要进行split提取特征
        # 其他特征可以直接由 string 转化为 float
        
        src = str(row[0])
        dst = str(row[1])
        fea = list(np.array(row[2], dtype=np.float32))

        return (src, dst, fea)

    def tensor_tuple_types(self):
        """ type tuple of parse function return
        """
        return (tf.string, tf.string, tf.float32)
